version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5433:5432
  etl_project:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env